# Generated by Django 5.0.6 on 2024-05-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_korisnik_options_alter_predmet_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korisnik',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
