# Generated by Django 5.0.6 on 2024-05-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_korisnik_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korisnik',
            name='role',
            field=models.CharField(choices=[('prof', 'profesor'), ('stu', 'student'), ('adm', 'admin')], default='stu', max_length=50),
        ),
        migrations.AlterField(
            model_name='korisnik',
            name='status',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('izv', 'izvanredni student'), ('red', 'redovni student')], default='none', max_length=50),
        ),
    ]
