# Generated by Django 5.0.6 on 2024-06-12 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_korisnik_role_alter_korisnik_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predmet',
            name='korisnik_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='upis',
            name='status',
            field=models.CharField(choices=[('izg', 'Izgubljen potpis'), ('potne', 'Potpisan, nije položen'), ('pol', 'Položen')], default='potne', max_length=50),
        ),
    ]
