# Generated by Django 5.0.6 on 2024-06-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_predmet_korisnik_id_alter_upis_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korisnik',
            name='status',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('izv', 'izvanredni student'), ('red', 'redovni student')], default='red', max_length=50),
        ),
    ]
